name: newflutterapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  geolocator: ^9.0.1
  geocoding: ^2.0.0
  mockito: ^5.4.1
  provider: ^6.0.1
  firebase_core: ^3.10.0
  firebase_auth: ^5.4.0
  cloud_firestore: ^5.6.1
  shared_preferences: ^2.0.18
  cupertino_icons: ^1.0.8
  image_picker: ^0.8.7+5
  firebase_storage: ^12.4.0
  flutter_vector_icons: ^2.0.0
  logging: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  
  firebase_core_web: ^2.19.0

flutter:
  uses-material-design: true