// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrAr3MURK1ODTxR7vsSsKmbM-KE4JxVoQ',
    appId: '1:809255004763:web:55e81d9e1d514dbf5ced7e',
    messagingSenderId: '809255004763',
    projectId: 'flutter-d3c58',
    authDomain: 'flutter-d3c58.firebaseapp.com',
    storageBucket: 'flutter-d3c58.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0DAOfljF-NwlqWmVg_3Ne5NC1cOAmgLg',
    appId: '1:809255004763:android:4c38909dba5b1ceb5ced7e',
    messagingSenderId: '809255004763',
    projectId: 'flutter-d3c58',
    storageBucket: 'flutter-d3c58.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPQex3_wJNfTr7D_OLtkiks_AdFRTagks',
    appId: '1:809255004763:ios:6a801cdf15a30f175ced7e',
    messagingSenderId: '809255004763',
    projectId: 'flutter-d3c58',
    storageBucket: 'flutter-d3c58.firebasestorage.app',
    iosBundleId: 'com.example.newflutterapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPQex3_wJNfTr7D_OLtkiks_AdFRTagks',
    appId: '1:809255004763:ios:6a801cdf15a30f175ced7e',
    messagingSenderId: '809255004763',
    projectId: 'flutter-d3c58',
    storageBucket: 'flutter-d3c58.firebasestorage.app',
    iosBundleId: 'com.example.newflutterapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrAr3MURK1ODTxR7vsSsKmbM-KE4JxVoQ',
    appId: '1:809255004763:web:2929915db6b6514a5ced7e',
    messagingSenderId: '809255004763',
    projectId: 'flutter-d3c58',
    authDomain: 'flutter-d3c58.firebaseapp.com',
    storageBucket: 'flutter-d3c58.firebasestorage.app',
  );

}